# Generated by Django 3.2.8 on 2021-11-08 19:40

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicFormPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('rows', models.JSONField()),
                ('parent_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='dynamic_forms.dynamicform')),
            ],
        ),
        migrations.CreateModel(
            name='NextRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_forms.dynamicformpage')),
                ('parent_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next', to='dynamic_forms.dynamicformpage')),
            ],
        ),
    ]
