# Generated by Django 3.2.8 on 2021-11-09 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dynamic_forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicFormResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_browser', models.CharField(max_length=20)),
                ('user_ip', models.CharField(max_length=15)),
                ('user_device', models.CharField(max_length=20)),
                ('date_finish', models.DateTimeField()),
                ('date_start', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('result_status', models.CharField(choices=[('Complete', 'Complete'), ('In Progress', 'In Progress'), ('Failed', 'Failed')], default='In Progress', max_length=15)),
                ('items', models.JSONField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='dynamic_forms.dynamicform')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
