# Generated by Django 3.2.8 on 2021-11-10 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dynamic_forms', '0002_dynamicformresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicformresult',
            name='date_finish',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='dynamicformresult',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL),
        ),
    ]
