# Generated by Django 3.2.8 on 2021-12-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0003_auto_20211110_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicformresult',
            name='user_browser',
        ),
        migrations.RemoveField(
            model_name='dynamicformresult',
            name='user_device',
        ),
        migrations.AddField(
            model_name='dynamicformresult',
            name='user_agent',
            field=models.TextField(default='PostmanRuntime/7.28.4'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dynamicformresult',
            name='user_ip',
            field=models.GenericIPAddressField(),
        ),
    ]
