# Generated by Django 3.2.8 on 2021-12-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0004_auto_20211203_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicformpage',
            name='is_success',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
