# Generated by Django 3.2.8 on 2021-12-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0005_dynamicformpage_is_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicformresult',
            name='user_agent',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dynamicformresult',
            name='user_ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
