# Generated by Django 3.2.8 on 2021-12-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0006_auto_20211208_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicformresult',
            name='date_finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
