# Generated by Django 3.2.8 on 2021-12-14 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0008_alter_dynamicformresult_result_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamicformpage',
            options={'ordering': ['pk']},
        ),
    ]
