# Generated by Django 3.2.8 on 2022-01-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0009_alter_dynamicformpage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextrules',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
