# Generated by Django 3.2.8 on 2022-01-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0010_nextrules_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamicformpage',
            options={'ordering': ['pos']},
        ),
        migrations.AddField(
            model_name='dynamicformpage',
            name='pos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='dynamicformpage',
            unique_together={('pos', 'parent_form')},
        ),
    ]
