# Generated by Django 3.2.8 on 2022-01-04 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("dynamic_forms", "0011_auto_20220103_2022"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dynamicformpage",
            name="is_success",
        ),
        migrations.RemoveField(
            model_name="nextrules",
            name="page",
        ),
        migrations.AddField(
            model_name="nextrules",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="nextrules",
            name="object_id",
            field=models.PositiveIntegerField(),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="DynamicFormSuccessPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("rows", models.JSONField()),
                ("link", models.URLField(null=True)),
                (
                    "parent_form",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="success_pages",
                        to="dynamic_forms.dynamicform",
                    ),
                ),
            ],
        ),
    ]
