# Generated by Django 3.2.11 on 2022-03-10 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0012_auto_20220104_2016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nextrules',
            options={'ordering': ['-priority']},
        ),
    ]
