# Generated by Django 3.2.11 on 2022-03-21 15:12

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0013_alter_nextrules_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nextrules',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='nextrules',
            name='object_id',
        ),
        migrations.AddField(
            model_name='dynamicformsuccesspage',
            name='rules',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nextrules',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic_forms.dynamicformpage'),
        ),
    ]
