# Generated by Django 3.2.11 on 2022-03-21 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0014_auto_20220321_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicformresult',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='dynamic_forms.dynamicform'),
        ),
    ]
