# Generated by Django 3.2.11 on 2022-03-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0015_alter_dynamicformresult_form'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamicformsuccesspage',
            options={'ordering': ['-priority']},
        ),
        migrations.AddField(
            model_name='dynamicformsuccesspage',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
