# Generated by Django 3.2.11 on 2022-08-03 19:18
from django.contrib.postgres.operations import HStoreExtension
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0016_auto_20220321_1952'),
    ]

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name='DynamicFormSubmitAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('action', models.CharField(choices=[
                 ('NA', 'No Action'), ('NEW_RESULT', 'New Result')], default='NA', max_length=15)),
                ('item_map', django.contrib.postgres.fields.hstore.HStoreField()),
                ('rules', django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(max_length=50), size=None)),
                ('new_result_form', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic_forms.dynamicform')),
                ('parent_form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                 related_name='submit_actions', to='dynamic_forms.dynamicform')),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
    ]
