# Generated by Django 3.2.11 on 2022-08-04 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0017_dynamicformsubmitaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dynamicformsubmitaction',
            old_name='action',
            new_name='type',
        ),
    ]
