# Generated by Django 3.2.11 on 2023-03-21 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0018_rename_action_dynamicformsubmitaction_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamicform',
            options={'ordering': ['pk']},
        ),
    ]
