# Generated by Django 3.2.11 on 2023-03-29 19:52

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0019_alter_dynamicform_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicformsubmitaction',
            name='email_body',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dynamicformsubmitaction',
            name='email_from',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='dynamicformsubmitaction',
            name='email_include_result',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dynamicformsubmitaction',
            name='email_reply_to',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, size=None),
        ),
        migrations.AddField(
            model_name='dynamicformsubmitaction',
            name='email_subject',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dynamicformsubmitaction',
            name='email_to',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, size=None),
        ),
        migrations.AddField(
            model_name='dynamicformsubmitaction',
            name='email_to_bcc',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, size=None),
        ),
        migrations.AddField(
            model_name='dynamicformsubmitaction',
            name='email_to_cc',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='dynamicformsubmitaction',
            name='item_map',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
        migrations.AlterField(
            model_name='dynamicformsubmitaction',
            name='rules',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='dynamicformsubmitaction',
            name='type',
            field=models.CharField(choices=[('NA', 'No Action'), ('NEW_RESULT', 'New Result'), ('EMAIL', 'Email')], default='NA', max_length=15),
        ),
    ]
