# Generated by Django 3.2.11 on 2023-04-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0020_auto_20230329_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicformsubmitaction',
            name='run_on_resubmit',
            field=models.BooleanField(default=False),
        ),
    ]
