# Generated by Django 4.2.1 on 2023-07-24 20:53

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0021_dynamicformsubmitaction_run_on_resubmit'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubmitAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('rules', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('run_on_resubmit', models.BooleanField(default=False)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('body', models.CharField(blank=True, max_length=500)),
                ('from_addr', models.EmailField(max_length=254)),
                ('to', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('to_bcc', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('to_cc', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('reply_to', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('include_result', models.BooleanField(default=False)),
                ('parent_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_actions', to='dynamic_forms.dynamicform')),
            ],
        ),
        migrations.CreateModel(
            name='NewResultSubmitAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('rules', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('run_on_resubmit', models.BooleanField(default=False)),
                ('item_map', django.contrib.postgres.fields.hstore.HStoreField(default=dict)),
                ('new_result_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_forms.dynamicform')),
                ('parent_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_result_actions', to='dynamic_forms.dynamicform')),
            ],
        ),
        migrations.DeleteModel(
            name='DynamicFormSubmitAction',
        ),
    ]
