# Generated by Django 4.2.1 on 2023-07-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0022_emailsubmitaction_newresultsubmitaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsubmitaction',
            name='body',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
