# Generated by Django 4.2.1 on 2024-04-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0025_alter_dynamicformresult_result_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsubmitaction',
            name='body',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
