# Generated by Django 4.2.1 on 2024-04-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0026_alter_emailsubmitaction_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsubmitaction',
            name='from_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
