# Generated by Django 4.2.1 on 2024-05-30 14:00

from django.db import migrations, models


def set_slug_default(apps, schema_editor):
    DynamicForm = apps.get_model("dynamic_forms", "dynamicform")
    for form in DynamicForm.objects.all().iterator():
        if form.slug == None:
            form.slug = f"{form.name.replace(' ', '-')}-{form.pk}"
            form.save()


def reverse_set_slug_default(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("dynamic_forms", "0027_emailsubmitaction_from_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="dynamicform",
            name="slug",
            field=models.SlugField(null=True),
        ),
        migrations.RunPython(set_slug_default, reverse_set_slug_default),
    ]
