# Generated by Django 4.2.1 on 2024-05-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0028_dynamicform_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicform',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
