# Generated by Django 4.2.1 on 2024-07-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0030_dynamicform_max_results_per_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultversion',
            name='description',
            field=models.TextField(default='Automatic'),
        ),
    ]
