# Generated by Django 4.2.1 on 2024-07-23 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0025_webhook'),
        ('dynamic_forms', '0031_alter_resultversion_description'),
    ]

    operations = [
    ]
