# Generated by Django 4.2.1 on 2024-07-23 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0032_merge_20240723_0941'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Webhook',
        ),
    ]
