# Generated by Django 4.2.1 on 2024-11-08 16:54

from django.db import migrations, models
import django.db.models.deletion


def set_root_page_default(apps, schema_editor):
    DynamicForm = apps.get_model("dynamic_forms", "dynamicform")
    DynamicFormPage = apps.get_model("dynamic_forms", "dynamicformpage")
    for form in DynamicForm.objects.all().iterator():
        if form.root_page == None:
            try:
                root = DynamicFormPage.objects.get(parent_form=form, pos=1)
            except DynamicFormPage.DoesNotExist:
                root = DynamicFormPage.objects.first()
            form.root_page = root
            form.save()


def reverse_set_root_page_default(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("dynamic_forms", "0033_delete_webhook"),
    ]

    operations = [
        migrations.AddField(
            model_name="dynamicform",
            name="root_page",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="dynamic_forms.dynamicformpage",
            ),
        ),
        migrations.RunPython(set_root_page_default, reverse_set_root_page_default),
    ]
