# Generated by Django 4.2.1 on 2024-11-08 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0034_dynamicform_root_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicform',
            name='root_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='dynamic_forms.dynamicformpage', unique=True),
        ),
    ]
