# Generated by Django 4.2.1 on 2024-11-08 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0035_alter_dynamicform_root_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamicformpage',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='dynamicformpage',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='dynamicformpage',
            name='pos',
        ),
    ]
