# Generated by Django 4.2.1 on 2024-11-18 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0036_alter_dynamicformpage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicform',
            name='root_page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='dynamic_forms.dynamicformpage'),
        ),
    ]
