# Generated by Django 3.2.11 on 2022-09-29 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import docxbuilder.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dynamic_forms', '0018_rename_action_dynamicformsubmitaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to=docxbuilder.models.user_dir_path)),
                ('visible_to', models.CharField(choices=[('Anyone', 'Anyone'), ('Owner', 'Just Me')], default='Owner', max_length=6)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('visible_to', models.CharField(choices=[('Anyone', 'Anyone'), ('Owner', 'Just Me')], default='Owner', max_length=6)),
                ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_sets', to='dynamic_forms.dynamicform')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('templates', models.ManyToManyField(related_name='sets', to='docxbuilder.Template')),
            ],
        ),
        migrations.AddConstraint(
            model_name='templateset',
            constraint=models.UniqueConstraint(condition=models.Q(('visible_to', 'Owner')), fields=('owner', 'name'), name='visible_to_owner'),
        ),
        migrations.AddConstraint(
            model_name='templateset',
            constraint=models.UniqueConstraint(condition=models.Q(('visible_to', 'Anyone')), fields=('name',), name='unique_template_set_name'),
        ),
    ]
