# Generated by Django 3.2.11 on 2022-10-07 20:39

import backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docxbuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='extra_fields',
            field=models.JSONField(default=list, validators=[backend.validators.JSONSchemaValidator(limit_value={'$schema': 'http://json-schema.org/draft-07/schema#', 'definitions': {'obj_list': {'items': {'properties': {'label': {'type': 'string'}, 'value': {'type': ['string', 'boolean', 'number', 'null', 'object']}}, 'required': ['label', 'value'], 'type': 'object'}, 'type': 'array'}}, 'items': {'properties': {'name': {'type': 'string'}, 'value': {'oneOf': [{'type': 'string'}, {'type': 'boolean'}, {'type': 'number'}, {'type': 'null'}, {'$ref': '#/definitions/obj_list'}]}}, 'required': ['name', 'value'], 'type': 'object'}, 'title': 'extra_fields', 'type': 'array'})]),
        ),
    ]
