# Generated by Django 3.2.11 on 2022-10-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docxbuilder', '0002_template_extra_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
