# Generated by Django 3.2.11 on 2023-03-21 16:59

import backend.validators
from django.db import migrations, models
import docxbuilder.models
import docxbuilder.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('docxbuilder', '0003_alter_template_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='extra_fields',
            field=models.JSONField(blank=True, default=list, validators=[backend.validators.JSONSchemaValidator(limit_value={'$schema': 'http://json-schema.org/draft-07/schema#', 'definitions': {'obj_list': {'items': {'properties': {'label': {'type': 'string'}, 'value': {'type': ['string', 'boolean', 'number', 'null', 'object']}}, 'required': ['label', 'value'], 'type': 'object'}, 'type': 'array'}}, 'items': {'properties': {'name': {'type': 'string'}, 'value': {'oneOf': [{'type': 'string'}, {'type': 'boolean'}, {'type': 'number'}, {'type': 'null'}, {'$ref': '#/definitions/obj_list'}]}}, 'required': ['name', 'value'], 'type': 'object'}, 'title': 'extra_fields', 'type': 'array'})]),
        ),
        migrations.AlterField(
            model_name='template',
            name='file',
            field=models.FileField(storage=docxbuilder.storage_backends.TemplateStorage(), upload_to=docxbuilder.models.user_dir_path),
        ),
    ]
