# Generated by Django 3.2.11 on 2023-05-08 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docxbuilder', '0004_auto_20230321_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='templateset',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='templateset',
            name='templates',
        ),
        migrations.CreateModel(
            name='TemplateRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(blank=True, max_length=256)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='docxbuilder.template')),
                ('template_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_rules', to='docxbuilder.templateset')),
            ],
        ),
    ]
