# Generated by Django 4.2.1 on 2023-08-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docxbuilder', '0005_auto_20230508_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='output_filename',
            field=models.CharField(default='{{filename}}', max_length=100),
            preserve_default=False,
        ),
    ]
