# Generated by Django 4.2.1 on 2023-08-30 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docxbuilder', '0006_template_output_filename'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='templateset',
            name='visible_to_owner',
        ),
        migrations.RemoveConstraint(
            model_name='templateset',
            name='unique_template_set_name',
        ),
    ]
