# Generated by Django 4.2.1 on 2023-11-30 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docxbuilder', '0007_remove_templateset_visible_to_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templateset',
            options={'ordering': ['id'], 'permissions': [('generate_docs', 'Can generate documents using this TemplateSet')]},
        ),
    ]
