# Generated by Django 4.2.1 on 2024-03-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docxbuilder', '0008_alter_templateset_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='generator',
            field=models.CharField(default='AUTO', max_length=50),
        ),
        migrations.AddField(
            model_name='template',
            name='preprocessor',
            field=models.CharField(default='NONE', max_length=50),
        ),
    ]
