# Generated by Django 4.2.1 on 2025-01-28 14:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docxbuilder', '0009_template_generator_template_preprocessor'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateset',
            name='rules',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
    ]
