# Generated by Django 4.2.1 on 2025-03-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docxbuilder', '0009_template_generator_template_preprocessor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='template',
            name='output_filename',
            field=models.CharField(max_length=200),
        ),
    ]
