# Generated by Django 4.2.1 on 2025-03-21 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docxbuilder', '0010_alter_template_name_alter_template_output_filename'),
        ('docxbuilder', '0010_templateset_rules'),
    ]

    operations = [
    ]
