# Generated by Django 4.2.1 on 2024-07-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('event', models.TextField(choices=[('NEW_RESULT_SUBMISSION', 'New Result Submission')])),
                ('hook_url', models.URLField()),
                ('params', models.JSONField()),
                ('name', models.TextField(max_length=100)),
            ],
        ),
    ]
