# Generated by Django 4.2.1 on 2023-07-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(choices=[(0, 'Client'), (1, 'Staff'), (2, 'Admin'), (3, 'Owner')], default=0),
        ),
    ]
