# Generated by Django 4.2.1 on 2024-05-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0027_emailsubmitaction_from_name'),
        ('accounts', '0003_userevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.SmallIntegerField(choices=[(0, 'Client'), (1, 'Staff'), (2, 'Admin'), (3, 'Owner')], default=0)),
                ('expiration_time', models.DateTimeField(null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('sent_time', models.DateTimeField(null=True)),
                ('accepted_time', models.DateTimeField(null=True)),
                ('subject', models.CharField(default='Invitation to join Barrow Brown Carrington, PLLC Client Portal', max_length=100)),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('initial_forms', models.ManyToManyField(blank=True, to='dynamic_forms.dynamicform')),
            ],
            options={
                'ordering': ['-created_time'],
                'permissions': [('invite_client', 'Can create UserInvitations for user with role == User.Role.Client'), ('invite_staff', 'Can create UserInvitations for users with role >= User.Role.Staff')],
            },
        ),
    ]
