# Generated by Django 4.2.1 on 2024-06-04 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
